### PR TITLE
Add CHANGELOG.md

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by sunetos** [comment]
Thanks, this is great! This is starting to turn into a real project.

**Comment by waldyrious** [comment]
Of course :) if we have the ability to plot stuff directly in the terminal, why depend exclusively on GUIs? [Progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) ftw!

In fact I'd even say this sort of lightweight plotting support [should come out of the box](http://stackoverflow.com/questions/14970817/plot-not-defined-with-julia) with Julia...

**Comment by sunetos** [comment]
I just added small comments throughout to try to make things a bit less obtuse for potential contributors: 5f540512dae3324a2d5170d4ab2199c9fcee934d

**Comment by sunetos** [comment]
And I tend to agree about the builtin light-weight plotting, but I'm obviously biased towards this particular package ;)

Gadfly + IPython will be far, far more convenient once bytecode caching prevents the 30-60 second Gadfly import delay of doom.

**Comment by waldyrious** [comment]
Yeah, but until then, TextPlots is a way better UX than "ERROR: plot not defined" :(
Re: the comments, that's great! Definitely makes it easier to jump into the code.

**Pull request merged**
