### PR TITLE
fix 0.4 compatible, remove Union datatypes, replace border

### PR DESCRIPTION
**Pull request by Evizero**
Hi!

is this package still of interest to you? I would need the plotting stuff for a project of mine, but I'd rather contribute here than create a reboot.

long story short, I made the package 0.3 and 0.4 compatible and replaced the borders with more appropriate unicode signs.

border

As I sidenode: I have also created a horizontal barplot, but that's not yet included here. I would however translate it to your package if there is interest. What do you think?

barplot

### CODE REVIEW

**Comment by waldyrious** [comment]
+:100: :)

**Comment by waldyrious** [comment]
Unfortunately @sunetos seems to have gone off the grid a few months ago. I would suggest you to move forward with your fork, merge the [open pull requests](https://github.com/sunetos/TextPlots.jl/pulls) to it if relevant, and submit a PR to METADATA.jl replacing this package with yours. If he eventually returns, it should be easy to merge the codebases if it's just a fast-forward to catch up with your commits.

**Comment by waldyrious** [comment]
In fact, it would be great if the owners of plotting packages joined under an organization, to prevent this sort of thing from happening in the future. For reference, the current plotting packages are:

Text-based plotting:
- @sunetos' [TextPlots.jl](https://github.com/sunetos/TextPlots.jl)
- @johnmyleswhite's [ASCIIPlots.jl](https://github.com/johnmyleswhite/ASCIIPlots.jl)
- @mbauman's [Sparklines.jl](https://github.com/mbauman/Sparklines.jl)

Graphical plotting:
- @dcjones' [Gadfly.jl](https://github.com/dcjones/Gadfly.jl)
- @stevengj's [PyPlot.jl](https://github.com/stevengj/PyPlot.jl)
- @nolta's [Winston.jl](https://github.com/nolta/Winston.jl)
- @mbaz's [Gaston.jl](https://github.com/mbaz/Gaston.jl)
- @Mononofu's [julia-plot](https://github.com/Mononofu/julia-plot)
- @SimonDanisch's [GLPlot.jl](https://github.com/SimonDanisch/GLPlot.jl)
- @tbreloff's [Qwt.jl](https://github.com/tbreloff/Qwt.jl)
- @bokeh's [Bokeh.jl](https://github.com/bokeh/Bokeh.jl)
- @plotly's [Plotly.jl](https://github.com/plotly/Plotly.jl)
- @jverzani's [GoogleCharts.jl](https://github.com/jverzani/GoogleCharts.jl)
- @johnmyleswhite's [Vega.jl](https://github.com/johnmyleswhite/Vega.jl)

Additionally, there are some graph-specific packages which I suppose would fit into a plotting organization, but since [JuliaGraphs](https://github.com/JuliaGraphs) exists, they should probably unite there:
- @Keno's [GraphViz.jl](https://github.com/Keno/GraphViz.jl)
- @sisl's [TikzGraphs.jl](https://github.com/sisl/TikzGraphs.jl)
- @IainNZ's [GraphLayout.jl](https://github.com/IainNZ/GraphLayout.jl)

It would be nice if the authors of those packages commented on the possibility of creating an organization, which would not only ensure that they won't get abandoned, but also make it easier to find the various plotting packages (it took me a while to collect the list above).

**Comment by Evizero** [comment]
Hmm well, I'll wait a day or two. The source code gave me an idea how to plot the lines etc a bit better. and the unicode list has some useful signs to possibly do pretty decent histograms. If this package is lost I'll probably do a full reboot.

**Comment by Evizero** [comment]
Your idea sounds better though

**Comment by IainNZ** [comment]
@waldyrious making an organization isn't really a solution to maintaining completely unmaintained packages - JuliaWeb has demonstrated this clearly now I think. Even if others have commit access, they don't necessarily have time or understanding to be merging PRs.
@Evizero I do suggest permanently forking if you'd be more willing to maintain.

**Comment by waldyrious** [comment]
@IainNZ at least for simple fixes (compatibility changes, readme edits, documentation, etc.) other people from the org could help, and the benefit of having the packages easily findable is also signigficant (for instance, http://julialang.org/downloads/plotting.html only mentions Gadfly and PyPlot)

**Comment by Evizero** [comment]
I took his idea - which is brilliant - but started from scratch which is much cleaner and yields more connected results.

sin

Since I don't use any of his code I'll just create a new package. I don't feel honest deleting the old code just for the name

**Comment by Evizero** [comment]
anyone still interested in REPL-plotting check out https://github.com/Evizero/UnicodePlots.jl

**Comment by tbreloff** [comment]
I agree with Iain that simply having an organization won't help too much, although I also agree that it would be nice to have a curated list of plotting packages (which I'm not sure would be accomplished by starting an organization)

I think we don't have clear winner for plotting yet, which means it would be great to have a document/tutorial that describes the pros/cons of the packages, compares usage for common workflows, dependencies, and features. If it makes sense to host this within a "JuliaPlot" group or something similar, then I'd be interested in contributing where I can. 

Maybe eventually this could help pool resources into "one package to rule them all", but that may be pipe dreaming...

**Comment by IainNZ** [comment]
@Evizero looks awesome

**Comment by waldyrious** [comment]
Regardless of whether an organization can promote such a convergence or not, it certainly can only help, not hurt. At worst we will have a situation just like right now, but with the benefit of having all plotting platforms in the same place. That's already a net positive. And simple PRs will be mergeable even if the maintainer becomes absent for a while. Another benefit. And at best, we have the chance to really improve the state of plotting in Julia, which arguably is a much more common need than web development, therefore hopefully commanding more interest and energy. So I see no downside to uniting the packages under an organization (unless I'm missing something?)

**Comment by waldyrious** [comment]
We might need to open a separate thread so that the closed status of this PR doesn't discourage people from commenting. We could reopen this one but neither the title nor the original content match the unification discussion, which was a kind of an off-branch out of the abandonment concerns. I'll start a new one.

**Pull request closed without merging**
