### PR TITLE
fix two bugs in the smart rounding code

### PR DESCRIPTION
**Pull request by waldyrious**
- the output of digits() is ordered from the least significant to the most, so it needs to be reversed
- fix a copy-paste overlook: log to log10
- also, add some code comments

### CODE REVIEW

**Comment by sunetos** [comment]
Thanks for the fix!

**Comment by waldyrious** [comment]
No problem, thanks for implementing it in the first place :) In fact, I might make my first package inspired in `findsymbolic()`, it's a [pretty interesting concept](https://en.wikipedia.org/wiki/Closed-form_expression#Conversion_from_numerical_forms).

**Comment by sunetos** [comment]
What would the package do? I'm interested in a somewhat related concept: canonical forms. I wonder if language supports a canonical version of each possible sentence, to help in NLP work.

 a d a m (via mobile)

**Comment by waldyrious** [comment]
Well, I was planning to experiment with emulating the tools mentioned in the link above (`identify` from [Maple](http://www.maplesoft.com/support/help/Maple/view.aspx?path=identify) and [SymPy](http://docs.sympy.org/latest/modules/mpmath/identification.html#mpmath.identify); ISC [v1](http://oldweb.cecm.sfu.ca/projects/ISC/ISCmain.html) and [v2](http://isc.carma.newcastle.edu.au/); and [RIES](http://mrob.com/pub/ries/index.html) -- the one used by Randall Munroe for [this xkcd comic](http://xkcd.com/1047/)), i.e. perform some sort of numeric-to-symbolic transformation, to get a [closed-form](https://en.wikipedia.org/wiki/Closed-form_expression) representation of a number, if possible.

The idea was to start small, basically what `findsymbolic` already does, plus some [`rationalize`](http://docs.julialang.org/en/latest/stdlib/base/#Base.rationalize) and maybe a few extra constants, and then gradually go up [hierarchy of mathematical expressions](https://en.wikipedia.org/wiki/Template:Mathematical_expressions) as well as adopting whatever other strategies SymPy or RIES are using. I wasn't sure how far along it would be feasible to go, but it seemed like a fun idea to try.

Eventually, it could even move beyond single numbers, and deal with vectors, in essence attempting to figure out the mathematical model most likely behind a stream of data, such as finding the equations governing an oscillating signal based on a bunch of measured samples (this kind of application is called [Symbolic regression](https://en.wikipedia.org/wiki/Symbolic_regression)).

---

Anyway, I am not sure how all these concepts could be generalized or even applied at all to NLP -- even mathematical language apparently is less regular than one might expect, [according](http://blog.wolframalpha.com/2014/08/12/computational-knowledge-and-the-future-of-pure-mathematics/) to Stephen Wolfram:

> Today the main way pure mathematics is described—say in papers—is through a mixture of [mathematical notation](http://www.stephenwolfram.com/publications/mathematical-notation-past-future/) and natural language, together with a few diagrams. And in designing a precise symbolic language for pure mathematics, this has to be the starting point.
> One might think that somehow mathematical notation would already have solved the whole problem. But there’s actually only a quite small set of constructs and concepts that can be represented with any degree of standardization in mathematical notation.

...but it would certainly be interesting to investigate.

**Comment by sunetos** [comment]
That sounds like a great project, and the Julia community is the perfect place to work on it. Once you've make some progress I'd recommend posting to [julia-users](https://groups.google.com/forum/#!forum/julia-users); there are probably folks there who have worked on similar things before.

**Comment by waldyrious** [comment]
Yeah, I follow the mailing list (mostly lurking) and will definitely post an ANN post as soon as I get something minimally useful, especially since I'm sure others will know better how to properly move towards the more advanced symbolic forms.

As for your thoughts on canonical forms and the application of the concept to NLP, I'd love to hear more about that.

**Comment by sunetos** [comment]
My idea for language canonical forms is still very informal; I'm experimenting with a few variations in Julia.

The basic idea is this: process a sentence/statement/document in multiple passes, transforming it as you go, and keeping extra metadata. More specifically: develop a strict subset of each major language in which each sentence can only be expressed one way (if possible), and retain the context of the original sentence for future transformations.

For example, take the sentence (typos intentional):
`She ain't got time for no messin' no-how.`

Tags:
`lang: en (confidence: 98%), locale: en/us (confidence: 91%), structure: sentence (confidence: 90%), formality: informal (confidence: 87%), dialect: southern (confidence: 60%)`

Canonical form:
`SHE NEVER HAS TIME FOR MISCHIEF.`

A computer-generated response then could interpret the meaning based on the strict canonical form, and choose to phrase its response in a matching formality/dialect, or in the formality/dialect of its assumed personality.

Response canonical form:
`I ASSERT THAT NOBODY DOES.`

Response, formal, southern:
`I declare, who does?`

Response, informal, southern:
`I reckon ain't nobody does.`

Response, informal, plain:
`I'd say nobody does.`

**Comment by waldyrious** [comment]
Very interesting. That reminds me a lot of [the work the guys from Wikipedia's Parsoid project are doing](http://blog.wikimedia.org/2013/03/04/parsoid-how-wikipedia-catches-up-with-the-web/) in order to process the messy, ad-hoc, context-sensitive wikitext markup into well-structured html. One of the key parts is indeed preserving metadata in the "canonical" html representation, so that two-way lossless transformations are possible (i.e. for WYSIWIG editing, they convert the wikitext into html, then need to save the result back in wikitext, without incurring in any of the potential ambiguity pitfalls). Of course, your idea is vastly more ambitious -- but precisely because of that, vastly more interesting, too.

I don't think work in a Julia project for language canonical forms would be related to the plans I outlined above for numeric-to-symbolic inference (I've seen that called "reverse calculation", too) in anything other than the high-level concept (but please correct me if I'm wrong), but nevertheless I'd be very curious to follow any developments you might make on that camp. Good luck!

**Comment by sunetos** [comment]
Thanks for the Parsoid reference; I didn't know about that! It definitely seems relevant.

**Comment by waldyrious** [comment]
Btw, still in the topic of this PR; would you mind tagging a new version of TextPlots, so the new rounding options are made available without checking out master?

**Comment by sunetos** [comment]
Done; v0.3.0 should be available in Julia.

**Pull request merged**
